# Generated by Django 5.0.7 on 2024-07-29 05:36

import ckeditor.fields
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='brand')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='model_name')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('image', models.ImageField(upload_to='image', verbose_name='image color')),
                ('hex_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='hex_code')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Color',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='media/slider_images', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'SliderImage',
                'verbose_name_plural': 'SliderImage',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='model_name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('inventory', models.BooleanField(default=False, verbose_name='inventory')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('screen_size', models.CharField(max_length=255, verbose_name='screen_size')),
                ('battery_capacity', models.CharField(max_length=255, verbose_name='battery_capacity')),
                ('camera_resolution', models.CharField(max_length=255, verbose_name='camera_resolution')),
                ('storage_capacity', models.CharField(max_length=255, verbose_name='storage_capacity')),
                ('ram', models.IntegerField(verbose_name='ram')),
                ('operating_system', models.CharField(max_length=50, verbose_name='operating_system')),
                ('image_default', models.ImageField(upload_to='image_default', verbose_name='image_default')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='shop.brand', verbose_name='brand')),
                ('colors', models.ManyToManyField(related_name='colors', to='shop.color', verbose_name='colors')),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobile',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.BooleanField(default=False, verbose_name='external')),
                ('internal', models.CharField(max_length=255, verbose_name='internal')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memory',
            },
        ),
        migrations.CreateModel(
            name='MainCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=550, verbose_name='camera')),
                ('features', models.CharField(max_length=500, verbose_name='features')),
                ('video', models.CharField(max_length=500, verbose_name='video')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maincamera', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'mainCamera',
                'verbose_name_plural': 'MainCamera',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.mobile', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=500, verbose_name='os')),
                ('cpu', models.CharField(max_length=500, verbose_name='cpu')),
                ('gpu', models.CharField(max_length=500, verbose_name='gpu')),
                ('chipset', models.CharField(max_length=500, verbose_name='chipset')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='function', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Function',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_display', models.CharField(max_length=500, verbose_name='type display')),
                ('resolution', models.CharField(blank=True, max_length=50, verbose_name='resolution')),
                ('screen_size', models.CharField(blank=True, max_length=50, verbose_name='screen_size')),
                ('anti_shock', models.BooleanField(default=False, verbose_name='anti_shock')),
                ('refresh_rate', models.CharField(blank=True, max_length=50, verbose_name='refresh_rate')),
                ('screen_always_on', models.BooleanField(default=False, verbose_name='screen_always_on')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Display',
                'verbose_name_plural': 'Display',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=500, verbose_name='dimensions')),
                ('weight', models.CharField(max_length=500, verbose_name='weight')),
                ('build', models.CharField(max_length=500, verbose_name='build')),
                ('sim', models.CharField(max_length=500, verbose_name='sim')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Body',
                'verbose_name_plural': 'Body',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_battery', models.CharField(max_length=500, verbose_name='type battery')),
                ('charging', models.CharField(max_length=500, verbose_name='charging')),
                ('battry_replacement', models.BooleanField(default=False, verbose_name='battry replacement')),
                ('wierles_charge', models.BooleanField(default=False, verbose_name='wierles charge')),
                ('fats_charge', models.BooleanField(default=False, verbose_name='fats charge')),
                ('time_charge', models.CharField(max_length=500, verbose_name='time charge')),
                ('otg_support', models.BooleanField(default=False, verbose_name='otg support')),
                ('max_wattage', models.CharField(max_length=225, verbose_name='max wattage')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Battery',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=255, verbose_name='technology')),
                ('bands_2g', models.CharField(max_length=255, verbose_name='bands_2g')),
                ('bands_3g', models.CharField(max_length=255, verbose_name='bands_3g')),
                ('bands_4g', models.CharField(max_length=255, verbose_name='bands_4g')),
                ('bands_5g', models.CharField(max_length=255, verbose_name='bands_5g')),
                ('speed', models.CharField(max_length=255, verbose_name='speed')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
        ),
        migrations.CreateModel(
            name='OtherFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc', models.BooleanField(default=False, verbose_name='nfc')),
                ('simcard', models.CharField(max_length=500, verbose_name='simcard')),
                ('bakup_5g', models.BooleanField(default=False, verbose_name='bakup_5g')),
                ('multiple_user', models.BooleanField(default=False, verbose_name='multiple_user')),
                ('version_usb', models.PositiveIntegerField(default=0, verbose_name='version_usb')),
                ('gps', models.BooleanField(default=False, verbose_name='gps')),
                ('wifi', models.CharField(max_length=500, verbose_name='wifi')),
                ('sensors', models.CharField(max_length=500, verbose_name='sensor')),
                ('voice_command', models.BooleanField(default=False, verbose_name='voice_command')),
                ('hotspot', models.BooleanField(default=False, verbose_name='hotspot')),
                ('language_support', models.PositiveIntegerField(default=0, verbose_name='language_support')),
                ('version_bluetooth', models.CharField(blank=True, max_length=50, verbose_name='version_bluetooth')),
                ('support_persian', models.BooleanField(default=False, verbose_name='support_persian')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ortherfeatures', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'OtherFeatures',
                'verbose_name_plural': 'OtherFeatures',
            },
        ),
        migrations.CreateModel(
            name='SelfieCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=550, verbose_name='camera')),
                ('features', models.CharField(max_length=500, verbose_name='features')),
                ('video', models.CharField(max_length=500, verbose_name='video')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='selficamera', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'SelfieCamera',
                'verbose_name_plural': 'SelfieCamera',
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.CharField(max_length=500, verbose_name='speaker_type')),
                ('jack_35_milimetr', models.BooleanField(default=False, verbose_name='jack_35_milimetr')),
                ('other', models.CharField(blank=True, max_length=500, verbose_name='other')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound', to='shop.mobile', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Sound',
                'verbose_name_plural': 'Sound',
            },
        ),
    ]
