# Generated by Django 5.0.7 on 2024-07-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'GalleryImage', 'verbose_name_plural': 'GalleryImage'},
        ),
    ]
